<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Home Page') }}
        </h2>
    </x-slot>

    <x-slot name='content1'>
        You are now logged in! Bruh.
        <p>Voluptate ad aute elit ea pariatur eiusmod consectetur tempor. Lorem id non culpa quis elit. Laborum irure incididunt voluptate proident anim id minim sint sit ex esse eiusmod deserunt. Enim et et voluptate irure quis veniam amet id ex eu ea enim cillum occaecat eu. Ullamco et tempor adipisicing velit do labore adipisicing sit mollit eiusmod consequat et consequat esse. Irure nostrud tempor ipsum. Magna duis reprehenderit commodo reprehenderit. Lorem aute consectetur do irure et culpa ex veniam aliquip nisi. Dolore consectetur enim commodo adipisicing labore. Duis elit eu ut deserunt fugiat duis officia pariatur.</p>
        <br />
        <p>Occaecat magna elit ipsum nisi deserunt cillum nostrud est deserunt veniam nulla. Enim exercitation et reprehenderit commodo veniam pariatur ad laboris officia nulla officia. Ut eiusmod sit proident. Sit ea do eiusmod deserunt sint laborum cillum fugiat nulla proident id. Quis id amet ullamco sint ut fugiat sit reprehenderit adipisicing. Non irure dolor amet elit aliqua ipsum voluptate. Cupidatat enim deserunt ullamco et exercitation elit do sunt dolore sit sunt pariatur. Consectetur cupidatat consequat aute reprehenderit reprehenderit nisi ullamco consequat et. Eiusmod minim esse laboris pariatur eu proident adipisicing aliqua elit amet. Lorem cupidatat dolor et aliquip.</p>
        <br />
        <p>Exercitation nostrud et commodo. Minim dolore velit ullamco laborum reprehenderit nostrud fugiat nostrud amet eiusmod in pariatur sunt. Et in velit tempor magna anim elit consequat. Id nulla consectetur enim tempor. Incididunt ea nulla pariatur voluptate esse laboris officia elit ut proident occaecat tempor laboris sunt incididunt. Consequat deserunt consequat est est enim veniam amet culpa voluptate. Est exercitation commodo cillum laboris ad irure sunt enim voluptate. Quis adipisicing sint veniam non. Eiusmod qui ullamco consectetur nostrud deserunt magna est. Velit cupidatat est cillum aliqua aliqua exercitation id occaecat eiusmod enim sunt dolor quis veniam.</p>
        <br />
        <p>Voluptate ad aute elit ea pariatur eiusmod consectetur tempor. Lorem id non culpa quis elit. Laborum irure incididunt voluptate proident anim id minim sint sit ex esse eiusmod deserunt. Enim et et voluptate irure quis veniam amet id ex eu ea enim cillum occaecat eu. Ullamco et tempor adipisicing velit do labore adipisicing sit mollit eiusmod consequat et consequat esse. Irure nostrud tempor ipsum. Magna duis reprehenderit commodo reprehenderit. Lorem aute consectetur do irure et culpa ex veniam aliquip nisi. Dolore consectetur enim commodo adipisicing labore. Duis elit eu ut deserunt fugiat duis officia pariatur.</p>
        <br />
    </x-slot>
    <x-slot name='content2'>
        <p>Occaecat magna elit ipsum nisi deserunt cillum nostrud est deserunt veniam nulla. Enim exercitation et reprehenderit commodo veniam pariatur ad laboris officia nulla officia. Ut eiusmod sit proident. Sit ea do eiusmod deserunt sint laborum cillum fugiat nulla proident id. Quis id amet ullamco sint ut fugiat sit reprehenderit adipisicing. Non irure dolor amet elit aliqua ipsum voluptate. Cupidatat enim deserunt ullamco et exercitation elit do sunt dolore sit sunt pariatur. Consectetur cupidatat consequat aute reprehenderit reprehenderit nisi ullamco consequat et. Eiusmod minim esse laboris pariatur eu proident adipisicing aliqua elit amet. Lorem cupidatat dolor et aliquip.</p>
        <br />
        <p>Exercitation nostrud et commodo. Minim dolore velit ullamco laborum reprehenderit nostrud fugiat nostrud amet eiusmod in pariatur sunt. Et in velit tempor magna anim elit consequat. Id nulla consectetur enim tempor. Incididunt ea nulla pariatur voluptate esse laboris officia elit ut proident occaecat tempor laboris sunt incididunt. Consequat deserunt consequat est est enim veniam amet culpa voluptate. Est exercitation commodo cillum laboris ad irure sunt enim voluptate. Quis adipisicing sint veniam non. Eiusmod qui ullamco consectetur nostrud deserunt magna est. Velit cupidatat est cillum aliqua aliqua exercitation id occaecat eiusmod enim sunt dolor quis veniam.</p>
        <br />
        <p>Voluptate ad aute elit ea pariatur eiusmod consectetur tempor. Lorem id non culpa quis elit. Laborum irure incididunt voluptate proident anim id minim sint sit ex esse eiusmod deserunt. Enim et et voluptate irure quis veniam amet id ex eu ea enim cillum occaecat eu. Ullamco et tempor adipisicing velit do labore adipisicing sit mollit eiusmod consequat et consequat esse. Irure nostrud tempor ipsum. Magna duis reprehenderit commodo reprehenderit. Lorem aute consectetur do irure et culpa ex veniam aliquip nisi. Dolore consectetur enim commodo adipisicing labore. Duis elit eu ut deserunt fugiat duis officia pariatur.</p>
        <br />
        <p>Occaecat magna elit ipsum nisi deserunt cillum nostrud est deserunt veniam nulla. Enim exercitation et reprehenderit commodo veniam pariatur ad laboris officia nulla officia. Ut eiusmod sit proident. Sit ea do eiusmod deserunt sint laborum cillum fugiat nulla proident id. Quis id amet ullamco sint ut fugiat sit reprehenderit adipisicing. Non irure dolor amet elit aliqua ipsum voluptate. Cupidatat enim deserunt ullamco et exercitation elit do sunt dolore sit sunt pariatur. Consectetur cupidatat consequat aute reprehenderit reprehenderit nisi ullamco consequat et. Eiusmod minim esse laboris pariatur eu proident adipisicing aliqua elit amet. Lorem cupidatat dolor et aliquip.</p>
        <br />
        <p>Exercitation nostrud et commodo. Minim dolore velit ullamco laborum reprehenderit nostrud fugiat nostrud amet eiusmod in pariatur sunt. Et in velit tempor magna anim elit consequat. Id nulla consectetur enim tempor. Incididunt ea nulla pariatur voluptate esse laboris officia elit ut proident occaecat tempor laboris sunt incididunt. Consequat deserunt consequat est est enim veniam amet culpa voluptate. Est exercitation commodo cillum laboris ad irure sunt enim voluptate. Quis adipisicing sint veniam non. Eiusmod qui ullamco consectetur nostrud deserunt magna est. Velit cupidatat est cillum aliqua aliqua exercitation id occaecat eiusmod enim sunt dolor quis veniam.</p>
        <br />
    </x-slot>
</x-app-layout>
